# Generated by Django 2.2.5 on 2020-01-17 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='myjob',
            new_name='userid',
        ),
        migrations.AddField(
            model_name='list',
            name='birth',
            field=models.IntegerField(null=True),
        ),
    ]
