# Generated by Django 2.2.5 on 2020-01-20 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200117_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='list',
            name='userid',
        ),
        migrations.AddField(
            model_name='list',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
