# Generated by Django 2.2.5 on 2020-01-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_list_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='birth_date',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
