--------------------------------------------------------
--  Constraints for Table SERVICE_NATIONDATATABLE
--------------------------------------------------------

  ALTER TABLE "GDP_PROJECT"."SERVICE_NATIONDATATABLE" ADD CONSTRAINT "SERVICE_NATIONDATATABLE_PK" PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "GDP_PROJECT"."SERVICE_NATIONDATATABLE" MODIFY ("CAPITAL" NOT NULL ENABLE);
  ALTER TABLE "GDP_PROJECT"."SERVICE_NATIONDATATABLE" MODIFY ("POPULATION" NOT NULL ENABLE);
  ALTER TABLE "GDP_PROJECT"."SERVICE_NATIONDATATABLE" MODIFY ("COUNTRYNAME" NOT NULL ENABLE);
  ALTER TABLE "GDP_PROJECT"."SERVICE_NATIONDATATABLE" MODIFY ("NO" NOT NULL ENABLE);
