# Generated by Django 2.2.5 on 2020-01-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20200120_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='성명'),
        ),
    ]
